name: "Hello Actions uwu"
description: "Greet someone"
author: "Misty Blunch"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Bby"
    
runs:
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: "mic"
  color: "pink"
