name: A workflow for my Hello Bby file
on: push

jobs:
  build:
    name: Hello Baby action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          MY_NAME: "MistyBlunch"
